### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by TeNNoX** [ymattw/coderev#9]
```
total 23895 files to check
Traceback (most recent call last):
  File "codediff.py", line 831, in <module>
    differ.make_diff()
  File "codediff.py", line 723, in make_diff
    self.__diff_dir()
  File "codediff.py", line 712, in __diff_dir
    self.__diff_dir_by_list()
  File "codediff.py", line 612, in __diff_dir_by_list
    from_lines = get_lines(obj1)
  File "codediff.py", line 69, in get_lines
    lines = [l.decode('utf-8') for l in fp.readlines()]
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 3: invalid continuation byte
```

Could be fixed by using `l.decode('utf-8', errors='replace')` (line 69) to replace unknown characters

**Comment by ymattw** [comment]
Fixed by #10.
